%%
plotSizeResponseByExperiment(pref_responses_stat_concat, pref_responses_stat_concat, ...
    red_ind_concat, green_ind_concat, targetCon,targetSize,exp_idx, nKeep_concat,'DayOrder',matchDrx, ...
    'UseDashedLines', [false, true], ...  % Dashed lines for the right plot
    'Titles', {'HTP+', 'HTP-'} ...
    , ...
    'YLabel', 'dF/F');

%%
plotSizeResponse_byCondition(pref_responses_loc_concat, pref_responses_loc_concat, ...
    red_ind_concat, green_ind_concat, targetCon, targetSize, runningByCondition, ...
    'DayOrder', matchDrx, ...
    'Titles', {'HTP+', 'HTP-'}, ...
    'YLabel', 'dF/F');