%% Experiment list for DART behavior
%% i2111
expt(1).mouse = 'i2111';
expt(1).date = '240125';
expt(1).folder = '2P';
expt(1).img_loc  = {'V1';'L2/3'};
expt(1).z = 235;
expt(1).obj = '16x';
expt(1).zoom = 2;
expt(1).frame_rate = 30;
expt(1).multiday_timesincedrug_hours = '0'
expt(1).multiday_matchdays = [];
expt(1).motionThreshold = 0.05;
expt(1).areaBorders = 0;
expt(1).indicator = {'virus';'GCaMP8'};
expt(1).drug = '';
expt(1).redChannelTag = {'tdTomato','membrane-HTP'};
expt(1).redChannelRun = '001';
expt(1).behavior_runs = {'003'};
expt(1).behavior_time = {'1144'};
expt(2).behavior_task = 'HAD_Context';
expt(1).data_loc = 'ACh';
expt(1).wheelColor = 'orange';
%% LW21
expt(2).mouse = "i'LW21'";
expt(2).date = '240109';
expt(2).folder = '2P';
expt(2).img_loc  = {'V1';'L2/3'};
expt(2).z = 197;
expt(2).obj = '16x';
expt(2).zoom = 2;
expt(2).frame_rate = 30;
expt(2).multiday_timesincedrug_hours = '0'
expt(2).multiday_matchdays = [];
expt(2).motionThreshold = 0.05;
expt(2).areaBorders = 0;
expt(2).indicator = {'virus';'GCaMP8'};
expt(2).drug = '';
expt(2).redChannelTag = {'tdTomato','membrane-HTP'};
expt(2).redChannelRun = '006';
expt(2).behavior_runs = {'008'};
expt(2).behavior_time = {'1242'};
expt(2).behavior_task = 'SurroundTest_fakeMouse_allCorr';
expt(2).data_loc = 'ACh';
expt(2).wheelColor = 'orange';
%% i2143
expt(3).mouse = 'i2143';
expt(3).date = '240509';
expt(3).folder = '2P';
expt(3).img_loc  = {'V1';'L2/3'};
expt(3).z = 188;
expt(3).obj = '16x';
expt(3).zoom = 1.7;
expt(3).frame_rate = 30;
expt(3).multiday_timesincedrug_hours = '0'
expt(3).multiday_matchdays = [];
expt(3).motionThreshold = 0.05;
expt(3).areaBorders = 0;
expt(3).indicator = {'virus';'GCaMP8'};
expt(3).drug = '';
expt(3).redChannelTag = {'tdTomato'};
expt(3).redChannelRun = '001';
expt(3).behavior_runs = {'003'};
expt(3).behavior_time = {'1532'};
expt(3).behavior_task = 'SurroundTest_fakeMouse_allCorr';
expt(3).data_loc = 'ACh';
expt(3).wheelColor = 'orange';
%% i2140
expt(4).mouse = 'i2140';
expt(4).date = '240904';
expt(4).folder = '2P';
expt(4).img_loc  = {'V1';'L2/3'};
expt(4).z = 180;
expt(4).obj = '16x';
expt(4).zoom = 1.7;
expt(4).frame_rate = 30;
expt(4).multiday_timesincedrug_hours = '0'
expt(4).multiday_matchdays = [];
expt(4).motionThreshold = 0.05;
expt(4).areaBorders = 0;
expt(4).indicator = {'virus';'GCaMP8f'};
expt(4).drug = '';
expt(4).redChannelTag = {'dTomato'};
expt(4).redChannelRun = '001';
expt(4).behavior_runs = {'003'};
expt(4).behavior_time = {'1152'};
expt(4).behavior_task = 'HAD_context';
expt(4).passive_runs={'004'};
expt(4).passive_time={'1317'};
expt(4).passive_task={'SurroundTest_fakeMouse_allCorr'};
expt(4).data_loc = 'ACh';
expt(4).wheelColor = 'orange';

%% i2140
expt(5).mouse = 'i2140';
expt(5).date = '240905';
expt(5).folder = '2P';
expt(5).img_loc  = {'V1';'L2/3'};
expt(5).z = 180;
expt(5).obj = '16x';
expt(5).zoom = 1.7;
expt(5).frame_rate = 30;
expt(5).multiday_timesincedrug_hours = '0'
expt(5).multiday_matchdays = [];
expt(5).motionThreshold = 0.05;
expt(5).areaBorders = 0;
expt(5).indicator = {'virus';'GCaMP8f'};
expt(5).drug = '';
expt(5).redChannelTag = {'dTomato'};
expt(5).redChannelRun = '001';
expt(5).behavior_runs = {'002'};
expt(5).behavior_time = {'1151'};
expt(5).behavior_task = 'HAD_context';
expt(5).passive_runs={'003'};
expt(5).passive_time={'1310'};
expt(5).passive_task={'SurroundTest_fakeMouse_allCorr'};
expt(5).data_loc = 'ACh';
expt(5).wheelColor = 'orange';
%% i2140
expt(6).mouse = 'i2140';
expt(6).date = '240906';
expt(6).folder = '2P';
expt(6).img_loc  = {'V1';'L2/3'};
expt(6).z = 191;
expt(6).obj = '16x';
expt(6).zoom = 1.7;
expt(6).frame_rate = 30;
expt(6).multiday_timesincedrug_hours = '17'
expt(6).multiday_matchdays = [];
expt(6).motionThreshold = 0.05;
expt(6).areaBorders = 0;
expt(6).indicator = {'virus';'GCaMP8f'};
expt(6).drug = '';
expt(6).redChannelTag = {'dTomato'};
expt(6).redChannelRun = '001';
expt(6).behavior_runs = {'002'};
expt(6).behavior_time = {'1055'};
expt(6).behavior_task = 'HAD_context';
expt(6).passive_runs={'003'};
expt(6).passive_time={'1234'};
expt(6).passive_task={'SurroundTest_fakeMouse_allCorr'};
expt(6).data_loc = 'ACh';
expt(6).wheelColor = 'orange';
