% retOnly_fromRef.m
% Retinotopy analysis using masks and FOV from a separate reference run.
% Registers ret data to the reference FOV, applies reference masks,
% extracts timecourses, and filters to cells responsive in the reference run.
%
% ADAPT FOR DIFFERENT SETUPS:
%   - Recording hardware: see sbxread and stackRegGPU calls
%   - Stimulus timing: see photoFrameFinder_Sanworks and nOn/nOff usage
%   - Cell segmentation: mask_cell/mask_np are expected from Suite2P or similar
%   - Neuropil subtraction: skewness-based weight optimization can be swapped
%     for a fixed coefficient (e.g., np_w = 0.7) if preferred

clear all; clc; close all;

%% Parameters  ret run
mouse = 'i2239'
date = '260430'
time = '1136'
RetImgFolder = '002'    % imaging run folder for the retinotopy data
frame_rate = 15         % acquisition frame rate (Hz); used implicitly via nOn/nOff

% Reference run (provides FOV, masks, and responsive cell list)
% The reference run is typically a longer/higher-quality imaging session
% whose ROIs, neuropil masks, and responsive cell list are reused here
refRun  = '004';
refDate = date;   % change if reference is from a different date

% File path setup — adjust isilonName for your OS and server mount point
if computer == 'GLNXA64'
    isilonName = '/home/cc735@dhe.duke.edu/GlickfeldLabShare/All_staff';
else
    isilonName = 'Z:';
end
base       = fullfile(isilonName, '/home/ACh/Data/2p_data/');
fnOut_base = fullfile(isilonName, '/home/ACh/Analysis/2p_analysis/VIP_YM90K');

run_str = ['runs-' RetImgFolder];
ref_str = ['runs-' refRun];
fnOut   = fullfile(fnOut_base, mouse, date, RetImgFolder);
mkdir(fnOut)

%% Load retinotopy imaging data
% sbxread is specific to Scanbox (Bhaskaran lab) .sbx format
% Replace with your acquisition system's reader (e.g., tiffRead, ScanImage loader)
% Output expected: [rows x cols x frames], uint16
CD = fullfile(base, mouse, date, RetImgFolder);
cd(CD);
imgMatFile = [RetImgFolder '_000_000.mat'];
load(imgMatFile);       % loads 'info' struct with config fields
nframes = info.config.frames;
fprintf('Reading %d frames...\n', nframes)
data_temp = squeeze(sbxread([RetImgFolder '_000_000'], 0, nframes));

%% Load behavior data
% This loads the Psychophysics Toolbox / Sanworks behavioral output
% 'input' struct contains trial-by-trial stimulus parameters (Az, El, nScansOn, nScansOff)
% For a different behavioral system, remap: nOn (stim frames), nOff (blank/baseline frames),
% and the tGratingAzimuthDeg / tGratingElevationDeg fields used below
fName = fullfile(isilonName, '/Behavior/Data', ['data-' mouse '-' date '-' time '.mat']);
load(fName);
retino_input=input;
clear input
nOn  = retino_input.nScansOn;   % frames the stimulus was on per trial
nOff = retino_input.nScansOff;  % frames of blank surrounding each trial

%% Find stimulus onsets via photodiode
% photoFrameFinder_Sanworks detects photodiode TTL pulses from the Sanworks system
% Replace with your own onset-detection method if using a different DAQ
% Output: stimOns — vector of frame indices (1-based) when each trial begins
fprintf('Finding stimulus onsets via photodiode...\n')
[stimOns, ~] = photoFrameFinder_Sanworks(info.frame);
ntrials = length(stimOns);
fprintf('%d trials detected\n', ntrials)

%% Load reference FOV and masks
% These files are generated by your ROI segmentation pipeline (e.g., Suite2P, CNMF)
% and saved during the reference run analysis:
%   mask_cell: [rows x cols] integer label map, 0=background, 1..nCells=ROI indices
%   mask_np:   [rows x cols x nCells] binary neuropil annulus per cell
%   resp:      [nCells x 1] logical, true if cell was stimulus-responsive in ref run
%   input:     behavioral input struct from the reference run
fprintf('Loading reference FOV and masks from run %s...\n', refRun)
load(fullfile(fnOut_base, mouse, refDate, refRun,'regOuts&Img.mat'));   % loads data_avg
load(fullfile(fnOut_base, mouse, refDate, refRun, 'mask_cell.mat'));    % loads mask_cell, mask_np
load(fullfile(fnOut_base, mouse, refDate, refRun, 'resp_inds.mat'));    % loads resp (logical)
load(fullfile(fnOut_base, mouse, refDate, refRun, 'input.mat')); 
ref_input = input;
resp_ind = find(resp);  % linear indices of responsive cells

referenceFOV = data_avg;   % mean projection of reference run, used as registration target
nCells = max(mask_cell(:));
fprintf('%d cells loaded from reference run\n', nCells)

%% Register ret data to reference FOV
% stackRegGPU performs rigid (translation) registration using GPU acceleration
% Replace with your preferred registration method (e.g., NoRMCorre, imregister)
% Two-step: first align the ret mean image to the ref FOV, then apply that
% transform to all frames. This avoids drift within the ret run itself.
fprintf('Registering ret data to reference FOV...\n')
retAvrg = mean(data_temp, 3);
[~, retAvrg_reg] = stackRegGPU(retAvrg, referenceFOV);
[~, data_reg]    = stackRegGPU(data_temp, retAvrg_reg);
sz = size(data_reg);
clear data_temp retAvrg retAvrg_reg

% Validation figure: registered FOV with imported masks overlaid
% If masks look misaligned here, check registration or that refRun FOV matches
figure;
imagesc(mean(data_reg, 3)); colormap gray; caxis([200 4000])
hold on
bounds = bwboundaries(mask_cell > 0);
for i = 1:length(bounds)
    plot(bounds{i}(:,2), bounds{i}(:,1), 'r', 'LineWidth', 0.5)
end
title(sprintf('Registered FOV  %d imported masks', nCells))
set(gca, 'TickDir', 'out', 'XTick', [], 'YTick', []); box off

%% Pixel-level retinotopy heatmap (quickRet style)
% This is a diagnostic — computes dF/F per stimulus position at the pixel level
% (no cell segmentation). Useful for confirming retinotopic signal before cell analysis.
% celleqel2mat_padded unpacks cell arrays of varying-length trial vectors into a matrix;
% replace with cell2mat or your equivalent if stimulus log format differs
Az_pix  = celleqel2mat_padded(retino_input.tGratingAzimuthDeg);
El_pix  = celleqel2mat_padded(retino_input.tGratingElevationDeg);
Azs_pix = unique(Az_pix);
Els_pix = unique(El_pix);
if min(Els_pix) < 0, Els_pix = fliplr(Els_pix); end  % put most-negative elevation first
nStim_pix = length(Azs_pix) * length(Els_pix);

% For each stimulus position, average dF/F across repeats
% Baseline: nOff/2 frames immediately before onset
pix_dfof_avg = zeros(sz(1), sz(2), nStim_pix);
idx = 1;
for i_el = 1:length(Els_pix)
    for i_az = 1:length(Azs_pix)
        these = find(El_pix == Els_pix(i_el) & Az_pix == Azs_pix(i_az));
        imgs  = zeros(sz(1), sz(2), length(these));
        for k = 1:length(these)
            on = stimOns(these(k));
            if ~isnan(on) && (on - nOff/2 >= 1) && (on + nOn - 1 <= sz(3))
                baseF = mean(data_reg(:,:, on-nOff/2 : on-1), 3);
                stimF = mean(data_reg(:,:, on : on+nOn-1), 3);
                imgs(:,:,k) = (double(stimF) - double(baseF)) ./ double(baseF);
            end
        end
        pix_dfof_avg(:,:,idx) = mean(imgs, 3);
        idx = idx + 1;
    end
end

% Summarize each stimulus position by its mean response among pixels above threshold
pixThresh = 0.2 * max(pix_dfof_avg(:));
img_avg_resp_pix = zeros(1, nStim_pix);
for i = 1:nStim_pix
    img = pix_dfof_avg(:,:,i);
    img_avg_resp_pix(i) = mean(img(img > pixThresh));
end

% Reshape into a 2D grid (El x Az) with correct orientation for imagesc
respMatrix = fliplr(rot90(reshape(img_avg_resp_pix, length(Els_pix), length(Azs_pix)), 3));
figure('Name', 'Pixel heatmap');
imagesc(Azs_pix, flip(Els_pix), respMatrix);
set(gca, 'YDir', 'normal', 'TickDir', 'out'); box off; grid off
xlabel('Azimuth (deg)'); ylabel('Elevation (deg)');
colorbar
title('Pixel-avg dF/F heatmap')

%% Extract timecourses with neuropil subtraction
% stackGetTimeCourses extracts mean fluorescence within each ROI mask over time
% stackGroupProject temporally downsamples by factor 'down' (used only for np weight fitting)
% If you don't have neuropil masks, set np_w = 0.7 (standard fixed coefficient)
fprintf('Extracting timecourses...\n')
down          = 5;   % temporal downsampling factor for neuropil weight estimation
data_reg_down = stackGroupProject(data_reg, down);
data_tc       = stackGetTimeCourses(data_reg, mask_cell);
data_tc_down  = stackGetTimeCourses(data_reg_down, mask_cell);

np_tc      = zeros(sz(3), nCells);
np_tc_down = zeros(floor(sz(3)/down), nCells);
for i = 1:nCells
    np_tc(:,i)      = stackGetTimeCourses(data_reg, mask_np(:,:,i));
    np_tc_down(:,i) = stackGetTimeCourses(data_reg_down, mask_np(:,:,i));
    fprintf('  Cell %d / %d\n', i, nCells)
end
clear data_reg_down

% Estimate per-cell neuropil subtraction weight by maximizing skewness of residual
% (Kerlin et al. 2010 approach). Skewness peaks when neuropil contamination is removed
% because the true signal distribution is more right-skewed.
% Weights are constrained to [0.01, 1.0] in steps of 0.01.
ii = 0.01:0.01:1;
x  = zeros(100, nCells);
for i = 1:100
    x(i,:) = skewness(data_tc_down - tcRemoveDC(np_tc_down * ii(i)));
end
[~, ind] = max(x, [], 1);
np_w = 0.01 * ind;   % optimal weight per cell; tcRemoveDC removes DC offset before scaling

npSub_tc = data_tc - tcRemoveDC(np_tc) .* np_w;

%% Build trial matrix using PD onsets
% Aligns each trial's timecourse to its photodiode-detected onset.
% Window: [onset - nOff/2 : onset + nOn + nOff/2 - 1], total = nOn + nOff frames
% Trials that would exceed recording bounds are left as NaN.
fprintf('Building trial matrix from PD onsets...\n')
tc_mat = nan(nOn+nOff, nCells, ntrials);
for itrial = 1:ntrials
    on = stimOns(itrial);
    if ~isnan(on) && (on + nOn + nOff/2) <= size(npSub_tc, 1)
        tc_mat(:,:,itrial) = npSub_tc((on - nOff/2):(on - 1 + nOn + nOff/2), :);
    end
end

% Baseline: middle half of the pre-stimulus blank (avoids edge artifacts)
% Stim: frames from onset through end of stimulus period
baselineFrames = (nOff/4+1):nOff/2;
stimFrames     = (nOff/2+1):(nOff/2+nOn);

tc_f    = mean(tc_mat(baselineFrames, :, :), 1);   % baseline F per cell per trial
tc_dfof = (tc_mat - tc_f) ./ tc_f;                 % dF/F [frames x cells x trials]
clear tc_mat tc_f

%% Stimulus info
% Parse azimuth/elevation combinations from behavioral log
% Unique values define the retinotopy grid; Els is flipped so most-negative is first
% (consistent with typical screen layout where negative elevation = lower visual field)
Az  = celleqel2mat_padded(retino_input.tGratingAzimuthDeg);
El  = celleqel2mat_padded(retino_input.tGratingElevationDeg);
Azs = unique(Az);
Els = unique(El);
if min(Els) < 0, Els = fliplr(Els); end

% Build Stims matrix listing every (El, Az) combination in the same order
% used when stacking resp_by_stim below — must stay consistent
nStim = length(Azs) * length(Els);
Stims = zeros(nStim, 2);
idx = 1;
for iEl = 1:length(Els)
    for iAz = 1:length(Azs)
        Stims(idx,:) = [Els(iEl) Azs(iAz)];
        idx = idx + 1;
    end
end
fprintf('%d unique Az+El stimuli\n', nStim)

%% Response per Az/El combination
% ret_mean_resp: mean dF/F during stimulus window, [nCells x ntrials]
% resp_by_stim: trial-averaged response on the El x Az grid, [nEls x nAzs x nCells]
ret_mean_resp = squeeze(mean(tc_dfof(stimFrames, :, :), 1));

resp_by_stim = nan(length(Els), length(Azs), nCells);
for i_el = 1:length(Els)
    indE = find(El == Els(i_el));
    for i_az = 1:length(Azs)
        indA = find(Az == Azs(i_az));
        these_trials = intersect(indE, indA);
        resp_by_stim(i_el, i_az, :) = nanmean(ret_mean_resp(:, these_trials), 2);
    end
end

%% Weighted average preferred position
% Simple nonparametric estimate of RF center: weighted mean of Az/El grid positions,
% weighted by response magnitude (negatives zeroed out).
% Used as a fallback and for comparison with the Gaussian fit center below.
[azGrid, elGrid] = meshgrid(Azs, Els);
prefAzimDeg = nan(1, nCells);
prefElevDeg = nan(1, nCells);
for iCell = 1:nCells
    w = max(resp_by_stim(:,:,iCell), 0);
    total_w = sum(w(:));
    if total_w > 0
        prefAzimDeg(iCell) = sum(w(:) .* azGrid(:)) / total_w;
        prefElevDeg(iCell) = sum(w(:) .* elGrid(:)) / total_w;
    end
end
fprintf('%d/%d cells have NaN preferred position (all responses <= 0)\n', ...
    sum(isnan(prefAzimDeg)), nCells)

%% Build Ind_struct (trial indices per stimulus, needed for fitting)
% Ind_struct(iStim).all_trials lists which trial numbers correspond to each
% Az/El combination — used during the shuffle fitting loop below
Ind_struct = [];
for iStim = 1:nStim
    indE = find(El == Stims(iStim,1));
    indA = find(Az == Stims(iStim,2));
    Ind_struct(iStim).all_trials = intersect(indE, indA);
end

%% Fit retinotopy: 2D ellipse fits with shuffling
% Fits a 2D rotated Gaussian to each cell's response map.
% Parameters: [A, sigma_Az, sigma_El, Az0, El0, xi]
%   A = amplitude, Az0/El0 = center, sigma = width, xi = rotation angle
%
% Shuffling (Nshuf iterations) randomly resamples trials within each stimulus
% condition to build a null distribution for each fit parameter — used below
% to assess whether the fit is significantly better than chance.
%
% Fit_2Dellipse_ret_lbub and Fit_2Dellipse_ret_CC are external scripts that
% read: data, grid2, PLOTIT_FIT, SAVEALLDATA — and write: s (fit result struct)
fprintf('Begin fitting retinotopy data...\n')

resp_dFoverF = squeeze(mean(tc_dfof(stimFrames, :, :), 1));  % nCells x ntrials

[AzAz, ElEl]   = meshgrid(Azs, Els);
grid2.AzAz     = AzAz;
grid2.ElEl     = ElEl;
dAz = median(diff(Azs));
dEl = median(diff(Els));
% Fine grid for smooth contour rendering of fit surfaces
Az_vec00 = Azs(1):(dAz/10):Azs(end);
El_vec00 = Els(1):(dEl/10):Els(end);
[AzAz00, ElEl00]  = meshgrid(Az_vec00, El_vec00);
grid2.AzAz00 = AzAz00;
grid2.ElEl00 = ElEl00;

Nshuf   = 100;
% h_all flags which cells to shuffle-fit (only responsive cells, to save time)
h_all   = zeros(1, nCells);
h_all(resp_ind) = 1;
Fit_struct = [];
ret_run_str = run_str;

fprintf('Nshuf = %d\n', Nshuf)
for count_shuf = 0:Nshuf
    fprintf('count_shuf: %d/%d\n', count_shuf, Nshuf)
    Im_mat_USE = zeros(nCells, nStim);
    for iCond = 1:nStim
        ind_all = Ind_struct(iCond).all_trials;
        if count_shuf > 0
            % Bootstrap resample trials within condition (with replacement)
            ind_all_1 = ind_all(randsample(length(ind_all), length(ind_all), 1));
        else
            ind_all_1 = ind_all;   % true (unshuffled) data on iteration 0
        end
        Im_mat_USE(:,iCond) = mean(resp_dFoverF(:,ind_all_1), 2);
    end

    ifig  = 1;
    start = 1;
    for iCell = 1:nCells
        % Skip non-responsive cells during shuffle (no need to fit their null distributions)
        if count_shuf > 0 && h_all(1,iCell) == 0
            continue
        end
        a = Im_mat_USE(iCell,:);
        if max(a,[],2) > 0
            b    = reshape(a', length(Azs), length(Els));
            data = b';
            if count_shuf == 0
                PLOTIT_FIT  = 0;
                SAVEALLDATA = 1;   % save full fit output on the true data pass
                Fit_2Dellipse_ret_lbub
                eval(['Fit_struct(iCell).True.s_ = s;']);
            else
                PLOTIT_FIT  = 0;
                SAVEALLDATA = 0;   % only save essential fields for shuffle iterations
                Fit_2Dellipse_ret_CC
                eval(['Fit_struct(iCell).Shuf(count_shuf).s_ = s;']);
            end
        end
    end
    if count_shuf == 0
        Im_mat_true = Im_mat_USE;  % retain true responses for R2 calculation later
    end
end
fprintf('Shuffling done\n')
save(fullfile(fnOut, [date '_' mouse '_' run_str '_Fit_struct.mat']), 'Fit_struct', '-v7.3')

%% Goodness-of-fit assessment
% Method 1 (lbub): a fit is "good" if the 95% shuffle confidence interval
% for Az center and El center is narrower than 2x the stimulus step size.
% This tests whether the fitted RF position is more constrained than chance.
fprintf('Assessing goodness of fit\n')
fit_true_vec = NaN(nCells, 10);
for iCell = 1:nCells
    if ~isempty(Fit_struct(iCell).True)
        tmp = [Fit_struct(iCell).True.s_.x, ...
               Fit_struct(iCell).True.s_.Elhicut_50, ...
               Fit_struct(iCell).True.s_.Azhicut_50, ...
               Fit_struct(iCell).True.s_.Elhicut_10, ...
               Fit_struct(iCell).True.s_.Azhicut_10];
        fit_true_vec(iCell,:) = tmp;
    end
end

all_fit_ind = find(~isnan(fit_true_vec(:,4)));
[opt_Az, opt_El] = findOptimalStimLocation(fit_true_vec, all_fit_ind);

% Collect shuffle fit parameters into a [nCells x nPars x Nshuf] array
fit_shuf_vec = NaN(nCells, 10, Nshuf);
for count_shuf = 1:Nshuf
    for iCell = 1:nCells
        if ~isempty(Fit_struct(iCell).Shuf)
            tmp = [Fit_struct(iCell).Shuf(count_shuf).s_.x, ...
                   Fit_struct(iCell).Shuf(count_shuf).s_.Elhicut_50, ...
                   Fit_struct(iCell).Shuf(count_shuf).s_.Azhicut_50, ...
                   Fit_struct(iCell).Shuf(count_shuf).s_.Elhicut_10, ...
                   Fit_struct(iCell).Shuf(count_shuf).s_.Azhicut_10];
            fit_shuf_vec(iCell,:,count_shuf) = tmp;
        end
    end
end

% lbub = lower/upper bound of 95% CI from shuffle distribution
% dim3 of lbub_fits: 1=lb, 2=ub, 3=shuf mean, 4=true fit value, 5=shuf std
Npars         = size(fit_shuf_vec, 2);
lbub_fits     = NaN(nCells, Npars, 5);
alpha_bound   = 0.025;   % two-tailed 95% CI
ind_shuf_lb   = ceil(Nshuf * alpha_bound);
ind_shuf_ub   = ceil(Nshuf * (1-alpha_bound));
for iCell = 1:nCells
    for count2 = 1:Npars
        tmp = squeeze(fit_shuf_vec(iCell,count2,:));
        i_sorted = sort(tmp);
        lbub_fits(iCell,count2,1) = i_sorted(ind_shuf_lb);
        lbub_fits(iCell,count2,2) = i_sorted(ind_shuf_ub);
        lbub_fits(iCell,count2,3) = mean(i_sorted);
        lbub_fits(iCell,count2,5) = std(i_sorted);
    end
    lbub_fits(iCell,:,4) = fit_true_vec(iCell,:);   % true fit stored in slot 4
end

lbub_diff = lbub_fits(:,:,2) - lbub_fits(:,:,1);   % CI width per parameter

% Criterion: CI width for Az center (col 4) and El center (col 5) must each
% be less than 2 stimulus steps — tighten for stricter RF localization
goodfit_ind = [];
for iCell = 1:nCells
    if lbub_diff(iCell,4) < retino_input.gratingAzimuthStepDeg*2 && ...
       lbub_diff(iCell,5) < retino_input.gratingAzimuthStepDeg*2
        goodfit_ind = [goodfit_ind iCell];
    end
end

% Exclude cells whose RF center falls at the edge of the stimulus grid
% (likely unresolved RFs that extend beyond the presented range)
goodfit_ind2 = zeros(size(goodfit_ind));
for i = 1:length(goodfit_ind)
    if sum(round(lbub_fits(goodfit_ind(i),4,4)) == [min(Azs) max(Azs)]) || ...
       sum(round(lbub_fits(goodfit_ind(i),5,4)) == [min(Els) max(Els)])
        continue
    end
    goodfit_ind2(i) = goodfit_ind(i);
end
goodfit_ind = goodfit_ind2(goodfit_ind2 ~= 0);
clear goodfit_ind2
fprintf('%d good-fit cells (final, lbub)\n', length(goodfit_ind))

%% R-squared goodness-of-fit (alternative to lbub)
% Method 2: compute R² between fitted 2D Gaussian surface and actual response map.
% More interpretable than lbub; adjust r2_threshold to be more/less permissive.
% R² is computed on the full response map (all Az x El positions).
r2_threshold = 0.65;
r2_vec = nan(1, nCells);
for iCell = 1:nCells
    if isempty(Fit_struct(iCell).True)
        continue
    end
    x_fit = Fit_struct(iCell).True.s_.x;
    % Fit parameters: [A, sigma_Az, sigma_El, Az0, El0, xi]
    A       = x_fit(1);
    sig_az  = x_fit(2);
    sig_el  = x_fit(3);
    Az0     = x_fit(4);
    El0     = x_fit(5);
    xi      = x_fit(6);   % rotation angle (radians)
    % Rotate grid coordinates into the RF's principal axes before evaluating Gaussian
    az_rot  =  (azGrid - Az0) .* cos(xi) + (elGrid - El0) .* sin(xi);
    el_rot  = -(azGrid - Az0) .* sin(xi) + (elGrid - El0) .* cos(xi);
    fit_surf = A .* exp(-(az_rot.^2 ./ (2*sig_az^2) + el_rot.^2 ./ (2*sig_el^2)));
    actual   = resp_by_stim(:,:,iCell);
    ss_res   = sum((actual(:) - fit_surf(:)).^2);
    ss_tot   = sum((actual(:) - mean(actual(:))).^2);
    if ss_tot > 0
        r2_vec(iCell) = 1 - ss_res/ss_tot;
    end
end

goodfit_ind_r2 = find(r2_vec >= r2_threshold);
fprintf('%d good-fit cells (R2 >= %.2f)\n', length(goodfit_ind_r2), r2_threshold)

% Example cells: sample from goodfit and non-goodfit responsive cells for visual QC
rng('shuffle');
n_good_ex    = min(6, length(goodfit_ind));
non_good_ind = resp_ind(~ismember(resp_ind, goodfit_ind));
n_nongood_ex = min(3, length(non_good_ind));
ex_cells = [goodfit_ind(randperm(length(goodfit_ind), n_good_ex)), ...
            non_good_ind(randperm(length(non_good_ind), n_nongood_ex))'];
n_ex = length(ex_cells);

% Weighted average preferred position figure
figure('Name', 'Weighted average preferred position');
for i = 1:n_ex
    subplot(3, 3, i)
    imagesc(Azs, Els, resp_by_stim(:,:,ex_cells(i)))
    set(gca, 'YDir', 'normal', 'TickDir', 'out'); box off; grid off
    hold on
    plot(prefAzimDeg(ex_cells(i)), prefElevDeg(ex_cells(i)), 'r+', 'MarkerSize', 10, 'LineWidth', 2)
    is_good = ismember(ex_cells(i), goodfit_ind);
    title(sprintf('Cell %d%s', ex_cells(i), repmat('*', 1, is_good)))
    if i > 6, xlabel('Az (deg)'); end
    if mod(i,3) == 1, ylabel('El (deg)'); end
end
colormap parula

% 2D Gaussian fit figure (same cells, contours overlaid on response map)
figure('Name', '2D Gaussian fit');
for i = 1:n_ex
    subplot(3, 3, i)
    imagesc(Azs, Els, resp_by_stim(:,:,ex_cells(i)))
    set(gca, 'YDir', 'normal', 'TickDir', 'out'); box off; grid off
    hold on
    if ~isempty(Fit_struct(ex_cells(i)).True)
        x_fit_i  = Fit_struct(ex_cells(i)).True.s_.x;
        A_i      = x_fit_i(1);  sig_az_i = x_fit_i(2);  sig_el_i = x_fit_i(3);
        Az0_i    = x_fit_i(4);  El0_i    = x_fit_i(5);  xi_i     = x_fit_i(6);
        az_rot_i =  (AzAz00 - Az0_i) .* cos(xi_i) + (ElEl00 - El0_i) .* sin(xi_i);
        el_rot_i = -(AzAz00 - Az0_i) .* sin(xi_i) + (ElEl00 - El0_i) .* cos(xi_i);
        fit_surf_i = A_i .* exp(-(az_rot_i.^2 ./ (2*sig_az_i^2) + el_rot_i.^2 ./ (2*sig_el_i^2)));
        contour(Az_vec00, El_vec00, fit_surf_i, 3, 'w')
        plot(Az0_i, El0_i, 'w+', 'MarkerSize', 10, 'LineWidth', 2)
        r2_str = sprintf(' R=%.2f', r2_vec(ex_cells(i)));
    else
        r2_str = ' no fit';
    end
    is_good = ismember(ex_cells(i), goodfit_ind);
    title(sprintf('Cell %d%s%s', ex_cells(i), repmat('*', 1, is_good), r2_str))
    if i > 6, xlabel('Az (deg)'); end
    if mod(i,3) == 1, ylabel('El (deg)'); end
end
colormap parula

% Example RF maps split by cell type
% mask_label is a logical vector [nCells x 1]: true = HTP+ (labeled interneuron)
% Replace with your own cell-type label vector if using a different marker
HTP_cells   = logical(mask_label);
type_masks  = {HTP_cells, ~HTP_cells};
type_lbls   = {'HTP+', 'HTP-'};
type_clrs   = {[0.85 0.2 0.2], [0.2 0.65 0.2]};

for iType = 1:2
    type_resp_ind = resp_ind(type_masks{iType}(resp_ind));
    type_good_ind = goodfit_ind(type_masks{iType}(goodfit_ind));
    n_good_ex = min(15, length(type_good_ind));
    type_nongood_ind = type_resp_ind(~ismember(type_resp_ind, type_good_ind));
    n_nongood_ex = min(3, length(type_nongood_ind));
    if n_good_ex + n_nongood_ex == 0, continue; end
    ex_type = [type_good_ind(randperm(length(type_good_ind), n_good_ex)), ...
               type_nongood_ind(randperm(length(type_nongood_ind), n_nongood_ex))'];
    n_ex_type = length(ex_type);

    figure('Name', sprintf('%s example RFs', type_lbls{iType}), 'Position', [50 50 600 900]);
    for i = 1:n_ex_type
        subplot(6, 3, i)
        imagesc(Azs, Els, resp_by_stim(:,:,ex_type(i)))
        set(gca, 'YDir', 'normal', 'TickDir', 'out'); box off
        hold on
        if ~isempty(Fit_struct(ex_type(i)).True)
            x_fit_i  = Fit_struct(ex_type(i)).True.s_.x;
            A_i = x_fit_i(1); sig_az_i = x_fit_i(2); sig_el_i = x_fit_i(3);
            Az0_i = x_fit_i(4); El0_i = x_fit_i(5); xi_i = x_fit_i(6);
            az_rot_i =  (AzAz00 - Az0_i).*cos(xi_i) + (ElEl00 - El0_i).*sin(xi_i);
            el_rot_i = -(AzAz00 - Az0_i).*sin(xi_i) + (ElEl00 - El0_i).*cos(xi_i);
            fit_surf_i = A_i.*exp(-(az_rot_i.^2./(2*sig_az_i^2) + el_rot_i.^2./(2*sig_el_i^2)));
            contour(Az_vec00, El_vec00, fit_surf_i, 3, 'w')
            plot(Az0_i, El0_i, 'w+', 'MarkerSize', 10, 'LineWidth', 2)
            r2_str = sprintf(' R=%.2f', r2_vec(ex_type(i)));
        else
            r2_str = ' no fit';
        end
        is_good = ismember(ex_type(i), type_good_ind);
        title(sprintf('Cell %d%s%s', ex_type(i), repmat('*',1,is_good), r2_str), ...
            'Color', type_clrs{iType})
        if i > 15, xlabel('Az (deg)'); end
        if mod(i,3) == 1, ylabel('El (deg)'); end
    end
    colormap parula
    sgtitle(sprintf('%s cells (n=%d responsive, %d goodfit)', ...
        type_lbls{iType}, length(type_resp_ind), length(type_good_ind)))
end

% Extract fit-based RF center from lbub_fits
% lbub_fits layout: dim1=cell, dim2=parameter, dim3=1:lb,2:ub,3:shuf mean,4:true,5:shuf std
% col 4 = Az0 (fit center azimuth), col 5 = El0 (fit center elevation)
fitAzimDeg = lbub_fits(:, 4, 4)';  % 1 x nCells
fitElevDeg = lbub_fits(:, 5, 4)';

% Distance between fit center and weighted average (sanity check; should be small)
rf_dist = sqrt((fitAzimDeg(goodfit_ind) - prefAzimDeg(goodfit_ind)).^2 + ...
               (fitElevDeg(goodfit_ind) - prefElevDeg(goodfit_ind)).^2);

save(fullfile(fnOut, [date '_' mouse '_' run_str '_lbub_fits.mat']), ...
    'lbub_fits', 'lbub_diff', 'goodfit_ind', 'goodfit_ind_r2', 'r2_vec', 'resp_ind', 'fitAzimDeg', 'fitElevDeg', '-v7.3')

%% Filter outputs to responsive cells
% All downstream analysis variables are saved in two versions:
% full (all nCells) and _resp (filtered to cells that passed responsiveness criterion in ref run)
resp_by_stim_resp = resp_by_stim(:, :, resp_ind);
prefAzimDeg_resp  = prefAzimDeg(resp_ind);
prefElevDeg_resp  = prefElevDeg(resp_ind);
npSub_tc_resp     = npSub_tc(:, resp_ind);
tc_dfof_resp      = tc_dfof(:, resp_ind, :);
fprintf('%d/%d cells retained (responsive)\n', length(resp_ind), nCells)

%% Save
save(fullfile(fnOut, [date '_' mouse '_' run_str '_ret_fromRef.mat']), ...
    'resp_by_stim', 'resp_by_stim_resp', ...
    'prefAzimDeg',  'prefElevDeg', ...
    'prefAzimDeg_resp', 'prefElevDeg_resp', ...
    'npSub_tc', 'npSub_tc_resp', ...
    'tc_dfof',  'tc_dfof_resp', ...
    'resp_ind', 'goodfit_ind', 'goodfit_ind_r2', 'r2_vec', 'Azs', 'Els', 'Stims', ...
    'fitAzimDeg', 'fitElevDeg', '-v7.3')
fprintf('Saved to %s\n', fnOut)

%% Venn diagram: lbub vs R2 good-fit cells
% Compares the two goodness-of-fit criteria among responsive cells only
lbub_set = ismember(resp_ind, goodfit_ind);
r2_set   = ismember(resp_ind, goodfit_ind_r2);

n_lbub_only = sum( lbub_set & ~r2_set);
n_r2_only   = sum(~lbub_set &  r2_set);
n_both      = sum( lbub_set &  r2_set);
n_neither   = sum(~lbub_set & ~r2_set);

fprintf('lbub only: %d | R2 only: %d | both: %d | neither: %d\n', ...
    n_lbub_only, n_r2_only, n_both, n_neither)

figure;
pie([n_lbub_only, n_r2_only, n_both, n_neither], ...
    {sprintf('lbub only (n=%d)', n_lbub_only), ...
     sprintf('R only (n=%d)',   n_r2_only), ...
     sprintf('both (n=%d)',      n_both), ...
     sprintf('neither (n=%d)',   n_neither)})
colormap([0.2 0.5 0.8; 0.9 0.4 0.3; 0.5 0.3 0.7; 0.8 0.8 0.8])
title(sprintf('Good-fit cells (of %d responsive)', length(resp_ind)))

%% Nested circle diagram: total -> responsive -> goodfit
% Area of each circle is proportional to cell count (radius = sqrt(n/nCells))
figure;
theta = linspace(0, 2*pi, 300);

r_total = 1;
r_resp  = sqrt(length(resp_ind) / nCells);
r_good  = sqrt(length(goodfit_ind) / nCells);

patch(r_total*cos(theta), r_total*sin(theta), [0.85 0.85 0.85], 'EdgeColor', 'none'); hold on
patch(r_resp *cos(theta), r_resp *sin(theta), [0.4  0.6  0.85], 'EdgeColor', 'none')
patch(r_good *cos(theta), r_good *sin(theta), [0.2  0.45 0.7 ], 'EdgeColor', 'none')

text(0,  r_total-0.05, sprintf('all cells\nn=%d', nCells),           'HorizontalAlignment', 'center', 'VerticalAlignment', 'top', 'FontSize', 10)
text(0,  r_resp-0.05,  sprintf('responsive\nn=%d', length(resp_ind)), 'HorizontalAlignment', 'center', 'VerticalAlignment', 'top', 'FontSize', 10, 'Color', 'w')
text(0, -0.05,         sprintf('goodfit\nn=%d', length(goodfit_ind)), 'HorizontalAlignment', 'center', 'VerticalAlignment', 'top', 'FontSize', 10, 'Color', 'w')

axis equal off
title('Cell counts by criterion')

%% Compare RF centers from fits to selected stim location
% plotRFdistanceMap visualizes how well the chosen stimulus position covered each cell's RF
% Inputs: true fit parameters, goodfit indices, cell masks, and the reference run's Az/El
plotRFdistanceMap(lbub_fits(:,:,4), goodfit_ind, mask_cell, double(ref_input.gratingAzimuthDeg), double(ref_input.gratingElevationDeg));

%% Save all figures
figHandles = findall(0, 'Type', 'figure');
for i = 1:length(figHandles)
    fig = figHandles(i);
    figName = get(fig, 'Name');
    if isempty(figName)
        figName = sprintf('fig%d', fig.Number);
    else
        figName = sprintf('fig%d_%s', fig.Number, strrep(figName, ' ', '_'));
    end
    print(fig, fullfile(fnOut, [date '_' mouse '_' run_str '_' figName '.pdf']), '-dpdf', '-bestfit')
end
fprintf('Saved %d figures\n', length(figHandles))

%% Optimal stimulus position
% Recomputes optimal Az/El for future experiment targeting based on population RF centers
all_fit_ind = find(~isnan(fit_true_vec(:,4)));
[opt_Az, opt_El] = findOptimalStimLocation(fit_true_vec, all_fit_ind);