function RasterMatrix = OrganizeRasterNew(JuiceLicks)

% restructure JuiceLicks, a cell containing JuiceTimes and LickTimes generated by FindLicksNew, into a
% nx1 cell (n = # of juicetimes) for use with plotSpikeRaster.m
% MEH 3/2/21


stop = length(JuiceLicks(:,1));     %get number of Juice deliveries
%LickTimesCell = cell(1,stop);
RasterMatrix = cell(stop, 1);       % make an output cell that is right length- one row for each juice delivery

for m = 1:stop
    RasterMatrix{m,1}=JuiceLicks{m,2}-JuiceLicks{m,1};  % for every juice delivery, convert the times of licks to times to plot on the raster by centering them at 0 = time of juice deliverty
   
    
end
figure
plotSpikeRaster(RasterMatrix, 'PlotType', 'vertline'); % create the raster plot using a function someone else wrote.
xline(0,'b');
end